configurations:
  secret_keyname: 'BINANCE_SECRET'
  api_keyname: 'BINANCE_APIKEY'
  trade_with: 'USDT'
  rebalance:
    - 'BTC:40'
    - 'ETH:35'
    - 'LINK:15'
    - 'ADA:10'
  trading_pairs:
    - 'BTC:USDT'
    - 'ETH:BTC'
    - 'LINK:BTC'
    - 'ADA:BTC'
