configurations:
  secret_keyname: 'BINANCE_SECRET'
  api_keyname: 'BINANCE_APIKEY'
  trade_with: 'USDT'
  rebalance:
    - 'BTC:40'
    - 'ETH:35'
    - 'LINK:10'
    - 'ADA:5'
    - 'MANA:5'
    - 'CURVE:5'
  trading_pairs:
    - 'BTC:USDT'
    - 'ETH:BTC'
    - 'LINK:BTC'
    - 'ADA:BTC'
    - 'MANA:BTC'
    - 'CURVE:BTC'
