version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    command: sh # node has to be invoked manually (see README)
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
      - 9339:9339
    tty: true
    environment:
      - NODE_ENV=development
      - PORT=3001
      - GUARD=none
      - EXCHANGE=bitflyer
